### ISSUE TITLE
REST API documentation via OpenAPI

### ISSUE THREAD

**Issue by danielmarschall** [danielmarschall/oidplus#13]
There should be an OpenAPI documentation that is automatically generated from the `restApiInfo()` methods of the plugins. I don't have the time to study the OpenAPI specification, so maybe someone can help me with this task? Thank you very much!

**Comment by wehowski** [comment]
Hello Daniel,
as I know you are not a big friend of libraries/dependencies.
Although I suggest to take a look at https://github.com/cebe/php-openapi#writing-api-description-files
Maybe this helps?

I m not sure if I can promise any help, have to read the spec first ...

**Comment by MarieSnajderova** [comment]
Hello, 
Do you still working on that project and need API documentation? 
I would like to try working with API documentation. Maybe it will help and could contribute to your project. 
Marie

**Comment by danielmarschall** [comment]
Hello,
thank you very much for that offer! Yes, I still need help with the documentation. The current documentation is written in plain text, but it would be good if it could follow the OpenAPI specification (which is a bit too complex for me at the moment).

**Comment by danielmarschall** [comment]
Hello,

the field list is like this:

Please note that the fields are not actually described (I can do that later). My main issue is the OpenAPI data structure. If you could do this, then I can easily edit the explanations of the fields later. Thank you very much.



-   Receive
    -   **GET**  https://www.example.com/oidplus/rest/v1/objects/[ns]:[id]
    -   Input parameters
        -   _None_
    -   Output parameters
        -   status (<0 is error, >=0 is success)
        -   status_bits
        -   error (if an error occurred)
        -   ra_email
        -   comment
        -   iris (for OID only)
        -   asn1ids (for OID only)
        -   confidential
        -   title
        -   description
        -   children
        -   created
        -   updated
-   Re-Create
    -   **PUT**  https://www.example.com/oidplus/rest/v1/objects/[ns]:[id]
    -   Input parameters
        -   ra_email (optional)
        -   comment (optional)
        -   iris (optional)
        -   asn1ids (optional)
        -   confidential (optional)
        -   title (optional)
        -   description (optional)
    -   Output parameters
        -   status (<0 is error, >=0 is success)
        -   status_bits
        -   error (if an error occurred)
        -   inserted_id (if it was created)
-   Create
    -   **POST**  https://www.example.com/oidplus/rest/v1/objects/[ns]:[id]
    -   Input parameters
        -   ra_email (optional)
        -   comment (optional)
        -   iris (optional)
        -   asn1ids (optional)
        -   confidential (optional)
        -   title (optional)
        -   description (optional)
    -   Output parameters
        -   status (<0 is error, >=0 is success)
        -   status_bits
        -   error (if an error occurred)
        -   inserted_id
-   Update
    -   **PATCH**  https://www.example.com/oidplus/rest/v1/objects/[ns]:[id]
    -   Input parameters
        -   ra_email (optional)
        -   comment (optional)
        -   iris (optional)
        -   asn1ids (optional)
        -   confidential (optional)
        -   title (optional)
        -   description (optional)
    -   Output parameters
        -   status (<0 is error, >=0 is success)
        -   status_bits
        -   error (if an error occurred)
-   Remove
    -   **DELETE**  https://www.example.com/oidplus/rest/v1/objects/[ns]:[id]
    -   Input parameters
        -   _None_
    -   Output parameters
        -   status (<0 is error, >=0 is success)
        -   status_bits
        -   error (if an error occurred)

**Comment by Azuris2** [comment]
Hi Marie, 

Are you in the midst of working on this?

Hi Daniel, 

Just to clarify - would the response for the endpoints be a JSON/XML object containing the output parameters as key value pairs?

**Comment by danielmarschall** [comment]
Hello,
yes, it is a REST interface with the result being a JSON object. The "value" can be an array, not just a string.

**Comment by Ashleycodesseo** [comment]
Hey @danielmarschall if you still need help with the API documentation for this project, I'd be happy to help! Let me know and I will structure it for you and help you as you need! Thanks

**Comment by danielmarschall** [comment]
Hello @Ashleycodesseo , yes, I still need help with this.

The current "documentation" is this:


-   Receive
    -   **GET**  https://www.example.com/oidplus/rest/v1/objects/[ns]:[id]
    -   Input parameters
        -   _None_
    -   Output parameters
        -   status (<0 is error, >=0 is success)
        -   status_bits
        -   error (if an error occurred)
        -   ra_email
        -   comment
        -   iris (for OID only)
        -   asn1ids (for OID only)
        -   confidential
        -   title
        -   description
        -   children
        -   created
        -   updated
-   Re-Create
    -   **PUT**  https://www.example.com/oidplus/rest/v1/objects/[ns]:[id]
    -   Input parameters
        -   ra_email (optional)
        -   comment (optional)
        -   iris (optional)
        -   asn1ids (optional)
        -   confidential (optional)
        -   title (optional)
        -   description (optional)
    -   Output parameters
        -   status (<0 is error, >=0 is success)
        -   status_bits
        -   error (if an error occurred)
        -   inserted_id (if it was created)
-   Create
    -   **POST**  https://www.example.com/oidplus/rest/v1/objects/[ns]:[id]
    -   Input parameters
        -   ra_email (optional)
        -   comment (optional)
        -   iris (optional)
        -   asn1ids (optional)
        -   confidential (optional)
        -   title (optional)
        -   description (optional)
    -   Output parameters
        -   status (<0 is error, >=0 is success)
        -   status_bits
        -   error (if an error occurred)
        -   inserted_id
-   Update
    -   **PATCH**  https://www.example.com/oidplus/rest/v1/objects/[ns]:[id]
    -   Input parameters
        -   ra_email (optional)
        -   comment (optional)
        -   iris (optional)
        -   asn1ids (optional)
        -   confidential (optional)
        -   title (optional)
        -   description (optional)
    -   Output parameters
        -   status (<0 is error, >=0 is success)
        -   status_bits
        -   error (if an error occurred)
-   Remove
    -   **DELETE**  https://www.example.com/oidplus/rest/v1/objects/[ns]:[id]
    -   Input parameters
        -   _None_
    -   Output parameters
        -   status (<0 is error, >=0 is success)
        -   status_bits
        -   error (if an error occurred)





Please note that the fields are not actually described (I can do that later). My main issue is the OpenAPI data structure. If you could do this, then I can easily edit the explanations of the fields later. Thank you very much!

**Comment by Ashleycodesseo** [comment]
I got you. I'm working thru all the projects I've received today I will update you once I'm started on this on. Thank you!

**Comment by Ashleycodesseo** [comment]
hey @danielmarschall I'm working on the docs now. I'll let you know if I have any questions

**Comment by danielmarschall** [comment]
@Ashleycodesseo Thank you very much for your contribution. A Markdown documentation is something which I can include in the documentation folder of OIDplus. However, the actual problem I had was that I need an OpenAPI conform specification (Swagger, XML, ...), not a human-readable documentation

**Comment by Ashleycodesseo** [comment]
Ohhh ok I think I misunderstood what you needed. Sorry! I am studying how to make documentation for developer end users

**Comment by Jamibaraki** [comment]
Hi @danielmarschall, are you still looking for someone to work on this?
I can create an OpenAPI 3.1 compatible YAML doc for you based on the above information.
If so, please assign me and let me know where you want the YAML doc (root folder, docs folder, etc).

**Comment by danielmarschall** [comment]
Hello @Jamibaraki 

thank you for the offer! Yes, I still search for somebody who can create an OpenAPI doc for the "objects" REST API, and it will be also useful for other REST APIs in the future.

I have a question for better understanding:

- If I have two REST APIs (e.g. /rest/v1/objects and in the future /test/v1/config ), can there be two YAML files, once for the "v1 objects" API and one of the "v1 config" API? Or should these be merged (maybe server-side on the fly merge 2 YAML files to 1 YAML file) to one YAML describing both APIs?

- Do I understand correctly that I can offer a download link to the YAML file(s), and that these YAML files can be useful for developers implementing the REST interface, i.e. is there a client software that would read such OpenAPI YAML files?
Or would the YAML file only make sense if a tool like Swagger is installed on the server-side (besides OIDplus) that visualizes the YAML file?

The YAML file for the "v1 objects" API can be saved in https://github.com/danielmarschall/oidplus/tree/master/plugins/viathinksoft/publicPages/000_objects


Thank you very much for your help!

**Comment by Jamibaraki** [comment]
Hi @danielmarschall ,

You can group endpoints with tags, so you could use that to present multiple APIs together in a single document if you wanted. Separate files works too though. It's up to you how you want to organize things. If the APIs are going to get larger then separate files makes more sense.

Presenting the files yourself using Swagger is standard, but there are plenty of ways to view YAML files so there's nothing wrong with just providing them separately.

**Comment by danielmarschall** [comment]
Feature is now implemented in SVN and synced to GitHub:
https://github.com/danielmarschall/oidplus/commit/8ec326b4fb92b55946a73a7110b63a1bec33630a

The YAML file is created on-the-fly, replacing the path with the system URL, and collecting all APIs from the plugins (currenty, only one plugin)

**Comment by danielmarschall** [comment]
Did a lot of more work:

- Swagger UI is now included directly into the OIDplus UI: https://hosted.oidplus.com/viathinksoft/?goto=oidplus%3Arest_api_documentation
- The specification has been converted from YAML to JSON, because this is much easier to parse in PHP without 3rd party libs. The Object API Specification: https://hosted.oidplus.com/dev/plugins/viathinksoft/publicPages/000_objects/openapi-3.1.0.json
- The resulting on-the-fly generated JSON is https://hosted.oidplus.com/viathinksoft/plugins/viathinksoft/publicPages/002_rest_api/openapi_json.php
