### ISSUE TITLE
Content-Security-Policy

### ISSUE THREAD

**Issue by wehowski** [danielmarschall/oidplus#16]
I got the error in the js console:
`Unrecognized Content-Security-Policy directive 'prefetch-src'.`
In OIDplus.class.php I commented out:
`				/*
   	"prefetch-src" => array(
				 	"'self'",
					 	"blob:"
				 	),`*/`
I'm not quite sure about this, first I thought it came from a plugin, but it also appears on the viathink-oidplus!?

**Comment by danielmarschall** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/prefetch-src ,
"prefetch-src" is non-standard and deprecated.

Deprecated are:
- [CSP: block-all-mixed-content](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/block-all-mixed-content)
Deprecated

- [CSP: plugin-types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/plugin-types)
Non-standardDeprecated

- [CSP: prefetch-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/prefetch-src)
Non-standardDeprecated

- [CSP: referrer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/referrer)
Non-standardDeprecated

- [CSP: report-uri](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-uri)
Deprecated


Non-Standard and not deprecated:

- [CSP: require-trusted-types-for](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/require-trusted-types-for)
Experimental

- [CSP: trusted-types](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/trusted-types)
Experimental


TODO: Remove them from `OIDplus::init()`

**Comment by danielmarschall** [comment]
Fixed in SVN Rev 1304
