### ISSUE TITLE
Implement illegality rules

### ISSUE THREAD

**Issue by danielmarschall** [danielmarschall/oidplus#78]
Illegality rules are available here:
- https://misc.daniel-marschall.de/oid-repository/api/oid_illegality_rules
- as well as in an undisclosed API to oid-info.com

Should we include a function in OIDplus to check if OIDs are illegal, and give the user a warning or error in case they want to use an illegal OID?

**Comment by wehowski** [comment]
One suggestion would be to show a warning for OIDplus admins and disallow/error for tenants/RAs?
Or another suggestion, illegal OIDs could be disabled until approved by admin?
Or, illegal OIDs could be treated as e.g. ObjectType "other" objects?

The last suggestion I would NOT prefer!?!

**Comment by danielmarschall** [comment]
Done in https://github.com/danielmarschall/oidplus/commit/a06d850a6edc6f94ee87faa4fcf3165846114a62
